//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelCompany
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Travel_companyEntities : DbContext
    {
        public Travel_companyEntities()
            : base("name=Travel_companyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Additional_feature> Additional_feature { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Hotel> Hotel { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Servic> Servic { get; set; }
        public virtual DbSet<Tour> Tour { get; set; }
        public virtual DbSet<Transport> Transport { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
    }
}
