//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelCompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int Code_tour { get; set; }
        public int Code_hotel { get; set; }
        public int Code_transport { get; set; }
        public string From_Where { get; set; }
        public string To_Where { get; set; }
        public int Number_of_people { get; set; }
        public System.DateTime Departure_date { get; set; }
        public System.DateTime Arrival_date { get; set; }
        public double Price { get; set; }
        public string Descriptions { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual Transport Transport { get; set; }
        public override string ToString() => Convert.ToString(Code_tour);
    }
}
